from cartagen.algorithms.buildings.amalgamation import morphological_amalgamation
from cartagen.algorithms.buildings.displacement import random_displacement
from cartagen.algorithms.buildings.regularization import rectangle_transformation, recursive_regression
from cartagen.algorithms.buildings.simplification import simplify_building
from cartagen.algorithms.buildings.squaring import square_polygon_ls, square_polygon_naive